site:
  title: Hashgraph DID-SDK
  url: https://swiss-digital-assets-institute.github.io/hashgraph-did-sdk-js
  start_page: developer::getting-started/introduction.adoc
content:
  sources:
    - url: .
      start_paths: [docs/developer]
    - url: .
      start_paths: [docs/design]
asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
antora:
  extensions:
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        start_on_load: true
