name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    name: Run tests [Node v${{ matrix.node }}]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node and install dependencies
        uses: ./.github/actions/setup-npm-env
        with:
          node-version: ${{ matrix.node }}

      - name: Prepare Hiero Solo
        id: solo
        uses: hiero-ledger/hiero-solo-action@fbca3e7a99ce9aa8a250563a81187abe115e0dad # v0.16

      - name: Set environment variables
        run: |
          echo "HEDERA_OPERATOR_ID=${{ steps.solo.outputs.accountId }}"
          echo "HEDERA_OPERATOR_KEY=${{ steps.solo.outputs.privateKey }}"
          echo "ADMIN_KEY=${{ steps.solo.outputs.privateKey }}"
          echo "PUBLIC_KEY=${{ steps.solo.outputs.publicKey }}"

      - name: Run tests
        timeout-minutes: 15
        env:
          HEDERA_OPERATOR_ID: ${{ steps.solo.outputs.accountId }}
          HEDERA_OPERATOR_KEY: ${{ steps.solo.outputs.privateKey }}
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: pnpm test:ci

      - name: Report coverage
        uses: step-security/jest-coverage-report-action@d70fde6bf791cdc2294f8c462d128caaafd28cdf # v2.3.4
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
